### ISSUE TITLE
Not implemented: model.GraphLayer.get_i() & get_j()

### ISSUE THREAD

**Issue by Rich2333** [ihalage/Finder#1]
Hi,

When I tried to train a new model using the following command provided in README.md:  
  
python trainer.py --train-path data/databases/MP_2021_July_no_polymorph/formation_energy/train.csv --val-path data/databases/MP_2021_July_no_polymorph/formation_energy/val.csv --test-path data/databases/MP_2021_July_no_polymorph/formation_energy/test.csv --epochs 800 --batch-size 128 --train --test
  
python trainer.py --train-path data/databases/MP_2021_July_no_polymorph/bandgap/train.csv --val-path data/databases/MP_2021_July_no_polymorph/bandgap/val.csv --test-path data/databases/MP_2021_July_no_polymorph/bandgap/test.csv --epochs 1200 --batch-size 128 --train --test --use-crystal-structure)  
  
I was reminded that:   **AttributeError: 'GraphLayer' object has no attribute 'get_i'** 
   
How can I get the get_i() and get_j() functions?

The complete traceback is as follows:  

Traceback (most recent call last):
  File "E:\Finder-main\Finder\trainer.py", line 470, in <module>
    worker.train_model()
  File "E:\Finder-main\Finder\trainer.py", line 188, in train_model
    l, tmae = train_step(*batch)
  File "C:\ProgramData\Anaconda3\envs\finder\lib\site-packages\tensorflow\python\util\traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\ProgramData\Anaconda3\envs\finder\lib\site-packages\tensorflow\python\framework\func_graph.py", line 1147, in autograph_handler
    raise e.ag_error_metadata.to_exception(e)
AttributeError: in user code:

    File "E:\Finder-main\Finder\trainer.py", line 167, in train_step  *
        predictions = model(inputs, training=True)
    File "C:\ProgramData\Anaconda3\envs\finder\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler  **
        raise e.with_traceback(filtered_tb) from None

    AttributeError: Exception encountered when calling layer "finder" (type Finder).

    in user code:

        File "E:\Finder-main\Finder\model.py", line 237, in call  *
            x1 = self.conv1([x, a, e])
        File "C:\ProgramData\Anaconda3\envs\finder\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler  **
            raise e.with_traceback(filtered_tb) from None

        AttributeError: Exception encountered when calling layer "graph_layer" (type GraphLayer).

        in user code:

            File "C:\ProgramData\Anaconda3\envs\finder\lib\site-packages\spektral\layers\convolutional\message_passing.py", line 108, in call  *
                return self.propagate(x, a, e)
            File "C:\ProgramData\Anaconda3\envs\finder\lib\site-packages\spektral\layers\convolutional\message_passing.py", line 120, in propagate  *
                messages = self.message(x, **msg_kwargs)
            File "E:\Finder-main\Finder\model.py", line 162, in message  *
                x_i = self.get_i(x)

            **AttributeError: 'GraphLayer' object has no attribute 'get_i'** 

        Call arguments received:
          • inputs=['tf.Tensor(shape=(None, 200), dtype=float32)', '<tensorflow.python.framework.sparse_tensor.SparseTensor object at 0x000002D677E74340>', 'tf.Tensor(shape=(None, 20), dtype=float32)']
          • kwargs={'training': 'True'}

**Comment by ihalage** [comment]
Hi,

Thanks for spotting this. `get_i()` and `get_j()` methods are inherited from spektral's [MessagePassing](https://github.com/danielegrattarola/spektral/blob/5d97c2aca0426f0bcc5cad201a357f8799755e7d/spektral/layers/convolutional/message_passing.py#L16) super class. Just noticed that these two methods are renamed as `get_sourced()` and `get_targets()`, respectively, in the latest version (1.1.0). See [here](https://github.com/danielegrattarola/spektral/commit/797868a9141a30975d724c319d6ad185faef22f2#diff-be53af17a69aa89ace0dbd88d8c3529c99679620bfb8b3e7b32d0db2bd8f75ebL56) for the commit. 

Use the earlier version of spektral as given in `requirements.txt` file to avoid this error. I will try to update the repo soon.

`pip install spektral==1.0.7`

**Comment by Rich2333** [comment]
Thanks for your reply!

My spektral is 1.1.0, I've tried get_sourced() and get_targets() but they don't work either.
I'll try to use spektral == 1.0.7.

**Comment by ihalage** [comment]
The repo has been updated with the latest versions of dependencies.
